= Windows Event manifest binary format
Analysis of WEVT_TEMPLATE

:toc:
:toclevels: 4

:numbered!:
[abstract]
== Summary

Since Windows Vista, a Windows Event manifest can be stored in MZ, PE-COFF
executable (EXE) files in a resource named "WEVT_TEMPLATE". This specification
is based on publicly available work on the format and was enhanced by analyzing
test data.

This document is intended as a working document of the data format specification
for the libfwevt project.

Special thanks to A. Schuster for his excellent work on this format.

[preface]
== Document information

[cols="1,5"]
|===
| Author(s): | Joachim Metz <joachim.metz@gmail.com>
| Abstract: | This document contains information about the Windows Event manifest binary format.
| Classification: | Public
| Keywords: | Windows Event manifest, WEVT_TEMPLATE
|===

[preface]
== License

....
Copyright (C) 2011-2023, Joachim Metz <joachim.metz@gmail.com>.
Permission is granted to copy, distribute and/or modify this document under the
terms of the GNU Free Documentation License, Version 1.3 or any later version
published by the Free Software Foundation; with no Invariant Sections, no
Front-Cover Texts, and no Back-Cover Texts. A copy of the license is included
in the section entitled "GNU Free Documentation License".
....

[preface]
== Revision history

[cols="1,1,1,5",options="header"]
|===
| Version | Author | Date | Comments
| 0.0.1 | J.B. Metz | October 2011 | Initial version.
| 0.0.2 | J.B. Metz | October 2012 | Additional information regarding WEVT_TEMPLATE resource.
| 0.0.3 | J.B. Metz | November 2012 | Additional information regarding WEVT_TEMPLATE resource.
| 0.0.4 | J.B. Metz | December 2012 | Additional information regarding WEVT_TEMPLATE resource.
| 0.0.5 | J.B. Metz | August 2022 | Additional information regarding WEVT_TEMPLATE resource.
| 0.0.6 | J.B. Metz | December 2023 | Additional information regarding WEVT_TEMPLATE resource.
| 0.0.7 | J.B. Metz | December 2023 | Moved out of MZ, PE-COFF executable file format (EXE) documentation
| 0.0.8 | J.B. Metz | December 2023 | Additional information regarding WEVT_TEMPLATE resource.
|===

:numbered:
== Overview

Since Windows Vista, a Windows Event manifest can be stored in MZ, PE-COFF
executable (EXE) files in a resource named "WEVT_TEMPLATE".

[cols="1,5",options="header"]
|===
| Characteristics | Description
| Byte order | little-endian
| Date and time values |
| Character strings | ASCII strings are Single Byte Character (SBC) or Multi Byte Character (MBC) string stored with a codepage. Sometimes referred to as ANSI string representation. +
Though technically maybe incorrect, this document will use term (extended) ASCII string. +
Unicode strings are stored in UTF-16 little-endian without the byte order mark (BOM).
|===

== Instrumentation manifest

The instrumentation manifest is of variable size and consists of:

[cols="1,1,1,5",options="header"]
|===
| Offset | Size | Value | Description
| 0 | 4 | "CRIM" | Signature
| 4 | 4 | | Size +
Including the compiled resource instrumentation manifest header
| 8 | 2 | 3 | Major version
| 10 | 2 | 1 | Minor version
| 12 | 4 | | Number of event providers
| 16 | 20 x number | | Array of event provider descriptors
|===

Assumed is that CRIM stands for "Compiled resource instrumentation manifest",
but it could also be short for Crimson, which was the codename for the event
logging service in Windows Longhorn.

=== Event provider descriptor

The event provider is of variable size and consists of:

[cols="1,1,1,5",options="header"]
|===
| Offset | Size | Value | Description
| 0 | 16 | | Provider identifier +
Contains a GUID
| 16 | 4 | | Event provider data offset +
The offset is relative to the start of the instrumentation manifest
|===

== Event provider

The event provider is of variable size and consists of:

[cols="1,1,1,5",options="header"]
|===
| Offset | Size | Value | Description
| 0 | 4 | "WEVT" | Signature
| 4 | 4 | | Size +
Including the Windows event template header
| 8 | 4 | | Message-table identifier +
or 0xffffffff (-1) if not set
| 12 | 4 | | Number of provider element descriptors
| 16 | 4 | | Number of [yellow-background]*Unknown 32-bit values*
| 20 | 8 x number | | Provider element descriptors
| ... | ... | | [yellow-background]*Unknown 32-bit values (Empty value)*
|===

=== Provider element descriptor

The provider element descriptor is 8 bytes is size and consists of:

[cols="1,1,1,5",options="header"]
|===
| Offset | Size | Value | Description
| 0 | 4 | | Provider element offset +
The offset is relative to the start of the instrumentation manifest
| 4 | 4 | | [yellow-background]*Unknown*
|===

[yellow-background]*The provider element type is determined by its signature?*

== Keyword definitions

The keyword definitions are of variable size and consist of:

[cols="1,1,1,5",options="header"]
|===
| Offset | Size | Value | Description
| 0 | 4 | "KEYW" | Signature
| 4 | 4 | | Size +
Including the keyword definitions header
| 8 | 4 | | Number of keyword definitions
| 12 | ... | | Array of keyword definitions
| ... | ... | | Keyword data
|===

=== Keyword definition

A keyword definition is 16 bytes in size and consists of:

[cols="1,1,1,5",options="header"]
|===
| Offset | Size | Value | Description
| 0 | 8 | | Identifier (Bitmask)
| 8 | 4 | | Message-table identifier +
or 0xffffffff (-1) if not set
| 12 | 4 | | Data offset +
The offset is relative to the start of the instrumentation manifest
|===

=== Keyword data

The keyword data is of variable size and consists of:

[cols="1,1,1,5",options="header"]
|===
| Offset | Size | Value | Description
| 0 | 4 | | Size +
Includes the size itself
| 4 | ... | | String +
The string is formatted as UTF-16 little-endian with an end-of-string character
| ... | ... | | Alignment padding +
The data is 8-byte aligned
|===

== Level definitions

The level definitions are of variable size and consist of:

[cols="1,1,1,5",options="header"]
|===
| Offset | Size | Value | Description
| 0 | 4 | "LEVL" | Signature
| 4 | 4 | | Size +
The value includes the size of the header or is 0 if empty
| 8 | 4 | | Number of level definitions
| 12 | ... | | Array of level definitions
| ... | ... | | Level data
|===

=== Level definition

A level definition is 12 bytes in size and consists of:

[cols="1,1,1,5",options="header"]
|===
| Offset | Size | Value | Description
| 0 | 4 | | Identifier
| 4 | 4 | | Message-table identifier +
or 0xffffffff (-1) if not set
| 8 | 4 | | Data offset +
The offset is relative to the start of the instrumentation manifest
|===

=== Level data

The level data is of variable size and consists of:

[cols="1,1,1,5",options="header"]
|===
| Offset | Size | Value | Description
| 0 | 4 | | Size +
Includes the size itself
| 4 | ... | | String +
The string is formatted as UTF-16 little-endian with an end-of-string character
| ... | ... | | Alignment padding +
The data is 8-byte aligned
|===

== Maps definitions

The maps definitions are of variable size and consist of:

[cols="1,1,1,5",options="header"]
|===
| Offset | Size | Value | Description
| 0 | 4 | "MAPS" | Signature
| 4 | 4 | | Size +
Including the map definitions header
| 8 | 4 | | Number of map definitions
| 12 | 4 x (number - 1) | | Array of map definition data offsets +
The offset is relative to the start of the instrumentation manifest +
[yellow-background]*This array contains one entry less than the number of maps. The first map definition is implied to be stored directly after this array.*
| ... | ... | | Array of map definitions
| ... | ... | | Array of map stings
|===

=== Bitmap definition

A bitmap definition is [yellow-background]*Unknown* bytes in size and consists of:

[cols="1,1,1,5",options="header"]
|===
| Offset | Size | Value | Description
| 0 | 4 | "BMAP" | Signature
|===

[yellow-background]*TODO: BMAPS are used to define flags*

=== Value map definition

Value maps are used to define enumeration types.

A value map definition is of variable size and consists of:

[cols="1,1,1,5",options="header"]
|===
| Offset | Size | Value | Description
| 0 | 4 | "VMAP" | Signature
| 4 | 4 | | Size +
Including including the signature
| 8 | 4 | | Map string data offset +
The offset is relative to the start of the instrumentation manifest
| 12 | 4 | | Number of value map entries
| 16 | ... | | Array of value map entries
|===

==== Value map entry

A value map entry is 8 bytes in size and consists of:

[cols="1,1,1,5",options="header"]
|===
| Offset | Size | Value | Description
| 0 | 4 | | Identifier
| 4 | 4 | | Message-table identifier +
or 0xffffffff (-1) if not set
|===

=== Map string

The map string data is of variable size and consists of:

[cols="1,1,1,5",options="header"]
|===
| Offset | Size | Value | Description
| 0 | 4 | | Size +
Includes the size itself
| 4 | ... | | String +
The string is formatted as UTF-16 little-endian with an end-of-string character
|===

== Channel definitions

The channel definitions are of variable size and consist of:

[cols="1,1,1,5",options="header"]
|===
| Offset | Size | Value | Description
| 0 | 4 | "CHAN" | Signature
| 4 | 4 | | Size +
Including the channel definitions header
| 8 | 4 | | Number of channel definitions
| 12 | ... | | Array of channel definitions
| ... | ... | | Channel name
|===

=== Channel definition

A channel definition is 16 bytes in size and consists of:

[cols="1,1,1,5",options="header"]
|===
| Offset | Size | Value | Description
| 0 | 4 | | Identifier
| 4 | 4 | | Data offset +
The offset is relative to the start of the instrumentation manifest
| 8 | 4 | | [yellow-background]*Unknown (Value)*
| 12 | 4 | | Message-table identifier +
or 0xffffffff (-1) if not set
|===

=== [[channel_types]]Channel types

[cols="1,1,5",options="header"]
|===
| Value | Identifier | Description
| | | Admin
| | | Analytic
| | | Debug
| | | Operational
|===

=== Channel name

The channel name is of variable size and consists of:

[cols="1,1,1,5",options="header"]
|===
| Offset | Size | Value | Description
| 0 | 4 | | Size +
Includes the size itself
| 4 | ... | | String +
The string is formatted as UTF-16 little-endian with an end-of-string character
| ... | ... | | Alignment padding +
The data is 8-byte aligned
|===

== Event definitions

The event definitions are of variable size and consist of:

[cols="1,1,1,5",options="header"]
|===
| Offset | Size | Value | Description
| 0 | 4 | "EVNT" | Signature
| 4 | 4 | | Size +
Including the event definitions header
| 8 | 4 | | Number of event definitions
| 12 | 4 | | [yellow-background]*Unknown (Empty values)*
| 16 | ... | | Array of event definitions
| ... | [yellow-background]*28* | | [yellow-background]*Unknown*
|===

=== Event definition

An event definition is 48 bytes in size and consists of:

[cols="1,1,1,5",options="header"]
|===
| Offset | Size | Value | Description
| 0 | 2 | | Identifier +
The event identifier without Customer flags and Severity.
| 2 | 1 | | Version
| 3 | 1 | | Channel
| 4 | 1 | | Level
| 5 | 1 | | Opcode
| 6 | 2 | | Task
| 8 | 8 | | Keywords
| 16 | 4 | | Message identifier
| 20 | 4 | | Template definition offset +
The offset is relative to the start of the instrumentation manifest or 0 if not set
| 24 | 4 | | Opcode definition offset +
The offset is relative to the start of the instrumentation manifest or 0 if not set
| 28 | 4 | | Level definition offset +
The offset is relative to the start of the instrumentation manifest or 0 if not set
| 32 | 4 | | Task definition offset +
The offset is relative to the start of the instrumentation manifest or 0 if not set
| 36 | 4 | | [yellow-background]*Unknown (number of 4 byte values?)*
| 40 | 4 | | [yellow-background]*Unknown (Offset to a 4 byte value?)*
| 44 | 4 | | [yellow-background]*Unknown (Flags)*
|===

== Keyword definitions

The keyword definitions are of variable size and consist of:

[cols="1,1,1,5",options="header"]
|===
| Offset | Size | Value | Description
| 0 | 4 | "KEYW" | Signature
| 4 | 4 | | Size +
Including the keyword definitions header
| 8 | 4 | | Number of keyword definitions
| 12 | ... | | Array of keyword definitions
| ... | ... | | Keyword data
|===

=== Keyword definition

A keyword definition is 16 bytes in size and consists of:

[cols="1,1,1,5",options="header"]
|===
| Offset | Size | Value | Description
| 0 | 8 | | Identifier (Bitmask)
| 8 | 4 | | Message-table identifier +
or 0xffffffff (-1) if not set
| 12 | 4 | | Data offset +
The offset is relative to the start of the instrumentation manifest
|===

=== Keyword data

The keyword data is of variable size and consists of:

[cols="1,1,1,5",options="header"]
|===
| Offset | Size | Value | Description
| 0 | 4 | | Size +
Includes the size itself
| 4 | ... | | String +
The string is formatted as UTF-16 little-endian with an end-of-string character
| ... | ... | | Alignment padding
The data is 8-byte aligned
|===

== Opcode definitions

The opcode definitions are of variable size and consist of:

[cols="1,1,1,5",options="header"]
|===
| Offset | Size | Value | Description
| 0 | 4 | "OPCO" | Signature
| 4 | 4 | | Size +
The value includes the size of the header or is 0 if empty
| 8 | 4 | | Number of opcode definitions
| 12 | ... | | Array of opcode definitions
|===

=== Opcode definition

A opcode definition is 12 bytes in size and consists of:

[cols="1,1,1,5",options="header"]
|===
| Offset | Size | Value | Description
| 0 | 4 | | Identifier
| 4 | 4 | | Message-table identifier +
or 0xffffffff (-1) if not set
| 8 | 4 | | Data offset +
The offset is relative to the start of the instrumentation manifest
|===

=== Opcode data

The opcode data is of variable size and consists of:

[cols="1,1,1,5",options="header"]
|===
| Offset | Size | Value | Description
| 0 | 4 | | Size +
Includes the size itself
| 4 | ... | | String +
The string is formatted as UTF-16 little-endian with an end-of-string character
| ... | ... | | Alignment padding +
The data is 8-byte aligned
|===

== Task

The task definitions are of variable size and consist of:

[cols="1,1,1,5",options="header"]
|===
| Offset | Size | Value | Description
| 0 | 4 | "TASK" | Signature
| 4 | 4 | | Size +
Including the task definitions header
| 8 | 4 | | Number of task definitions
| 12 | ... | | Array of task definitions
| ... | ... | | Task data
|===

=== Task definition

A task definition is 28 bytes in size and consists of:

[cols="1,1,1,5",options="header"]
|===
| Offset | Size | Value | Description
| 0 | 4 | | Identifier
| 4 | 4 | | Message-table identifier +
or 0xffffffff (-1) if not set
| 8 | 16 | | [yellow-background]*Unknown (MUI identifier)* +
Contains a GUID
| 24 | 4 | | Data offset +
The offset is relative to the start of the instrumentation manifest
|===

=== Task data

The task data is of variable size and consists of:

[cols="1,1,1,5",options="header"]
|===
| Offset | Size | Value | Description
| 0 | 4 | | Size +
Includes the size itself
| 4 | ... | | String +
The string is formatted as UTF-16 little-endian with an end-of-string character
| ... | ... | | Alignment padding +
The data is 8-byte aligned
|===

== Template table

The template table is of variable size and consists of:

[cols="1,1,1,5",options="header"]
|===
| Offset | Size | Value | Description
| 0 | 4 | "TTBL" | Signature
| 4 | 4 | | Size +
Including the template table header
| 8 | 4 | | Number of templates
| 12 | ... | | Array of templates
| ... | ... | | Template data
|===

=== Template definition

A template definition is of variable size and consists of:

[cols="1,1,1,5",options="header"]
|===
| Offset | Size | Value | Description
| 0 | 4 | "TEMP" | Signature
| 4 | 4 | | Size +
Including the template header
| 8 | 4 | | Number of item descriptors
| 12 | 4 | | Number of item names
| 16 | 4 | | Template items offset +
The offset is relative to the start of the instrumentation manifest
| 20 | 4 | | [yellow-background]*Unknown (flags?)* +
Seen 1 in most cases and 2 when UserData is set.
| 24 | 16 | | Identifier +
Contains a GUID
| 40 | ... | | Binary XML fragment
| ... | ... | | Template item descriptors
| ... | ... | | Template item names
|===

[NOTE]
If the number of item descriptors (and number of item names) the template items
offset is either 0 or contains the template size.

=== Template binary XML fragment

The binary XML is slightly different to that of EVTX.

* the name offset is not used
* the name does not contain the additional unknown 4 byte value
* the template items are stored outside the template

=== Template item descriptor

The template item descriptor is 20 bytes in size and consists of:

[cols="1,1,1,5",options="header"]
|===
| Offset | Size | Value | Description
| 0 | 4 | | [yellow-background]*Unknown (empty value)*
| 4 | 1 | | Input data type +
See section: <<template_item_input_data_type,Template item input data type>>
| 5 | 1 | | Output data type +
See section: <<template_item_output_data_type,Template item output data type>>
| 6 | 2 | | [yellow-background]*Unknown (empty value)*
| 8 | 4 | | [yellow-background]*Unknown (empty value)*
| 12 | 2 | | [yellow-background]*Unknown (empty value)*
| 14 | 2 | | Data size
| 16 | 4 | | Template item name offset +
The offset is relative to the start of the instrumentation manifest
|===

==== [[template_item_input_data_type]]Template item input data type

[cols="1,1,5",options="header"]
|===
| Value | Identifier | Description
| 0x01 | win:UnicodeString |
| 0x02 | win:AnsiString |
| 0x03 | win:Int8 |
| 0x04 | win:UInt8 |
| 0x05 | win:Int16 |
| 0x06 | win:UInt16 |
| 0x07 | win:Int32 |
| 0x08 | win:UInt32 |
| 0x09 | win:Int64 |
| 0x0a | win:UInt64 |
| 0x0b | win:Float |
| 0x0c | win:Double |
| 0x0d | win:Boolean |
| 0x0e | win:Binary |
| 0x0f | win:GUID |
| 0x10 | win:Pointer |
| 0x11 | win:FILETIME |
| 0x12 | win:SYSTEMTIME |
| 0x13 | win:SID |
| 0x14 | win:HexInt32 |
| 0x15 | win:HexInt64 |
|===

==== [[template_item_output_data_type]]Template item output data type

[cols="1,1,5",options="header"]
|===
| Value | Identifier | Description
| 0x01 | xs:string |
| 0x02 | xs:dateTime |
| 0x03 | xs:byte |
| 0x04 | xs:unsignedByte |
| 0x05 | xs:short |
| 0x06 | xs:unsignedShort |
| 0x07 | xs:int |
| 0x08 | xs:unsignedInt |
| 0x09 | xs:long |
| 0x0a | xs:unsignedLong |
| 0x0b | xs:float |
| 0x0c | xs:double |
| 0x0d | xs:boolean |
| 0x0e | xs:GUID |
| 0x0f | xs:hexBinary |
| 0x10 | win:HexInt8 |
| 0x11 | win:HexInt16 |
| 0x12 | win:HexInt32 |
| 0x13 | win:HexInt64 |
| 0x14 | win:PID |
| 0x15 | win:TID |
| 0x16 | win:Port |
| 0x17 | win:IPv4 |
| 0x18 | win:IPv6 |
| 0x19 | win:SocketAddress |
| 0x1a | win:CIMDateTime |
| 0x1b | win:ETWTIME |
| 0x1c | win:Xml |
| 0x1d | win:ErrorCode |
| 0x1e | win:Win32Error |
| 0x1f | win:NTSTATUS |
| 0x20 | win:HResult |
| 0x21 | win:DateTimeCultureInsensitive |
| 0x22 | win:Json |
| 0x23 | win:Utf8 |
| 0x24 | win:Pkcs7WithTypeInfo |
|===

=== Template item name

The template item name is of variable size and consists of:

[cols="1,1,1,5",options="header"]
|===
| Offset | Size | Value | Description
| 0 | 4 | | Size +
Includes the size itself
| 4 | ... | | String +
The string is formatted as UTF-16 little-endian with an end-of-string character
| ... | ... | | Alignment padding +
The data is 8-byte aligned +
[yellow-background]*Last name only?*
|===

:numbered!:
[appendix]
== References

[cols="1,5",options="header"]
|===
| Title: | EventManifest Schema
| URL: | https://learn.microsoft.com/en-us/windows/win32/wes/eventmanifestschema-schema
|===

[cols="1,5",options="header"]
|===
| Title: | Microsoft Windows Event Logging - Dokumentation der Binärformate
| Author(s): | A. Schuster
| Version: | 148
| Date: | February 6, 2011
|===

[appendix]
== GNU Free Documentation License

Version 1.3, 3 November 2008
Copyright © 2000, 2001, 2002, 2007, 2008 Free Software Foundation, Inc.
<http://fsf.org/>

Everyone is permitted to copy and distribute verbatim copies of this license
document, but changing it is not allowed.

=== 0. PREAMBLE

The purpose of this License is to make a manual, textbook, or other functional
and useful document "free" in the sense of freedom: to assure everyone the
effective freedom to copy and redistribute it, with or without modifying it,
either commercially or noncommercially. Secondarily, this License preserves for
the author and publisher a way to get credit for their work, while not being
considered responsible for modifications made by others.

This License is a kind of "copyleft", which means that derivative works of the
document must themselves be free in the same sense. It complements the GNU
General Public License, which is a copyleft license designed for free software.

We have designed this License in order to use it for manuals for free software,
because free software needs free documentation: a free program should come with
manuals providing the same freedoms that the software does. But this License is
not limited to software manuals; it can be used for any textual work,
regardless of subject matter or whether it is published as a printed book. We
recommend this License principally for works whose purpose is instruction or
reference.

=== 1. APPLICABILITY AND DEFINITIONS

This License applies to any manual or other work, in any medium, that contains
a notice placed by the copyright holder saying it can be distributed under the
terms of this License. Such a notice grants a world-wide, royalty-free license,
unlimited in duration, to use that work under the conditions stated herein. The
"Document", below, refers to any such manual or work. Any member of the public
is a licensee, and is addressed as "you". You accept the license if you copy,
modify or distribute the work in a way requiring permission under copyright law.

A "Modified Version" of the Document means any work containing the Document or
a portion of it, either copied verbatim, or with modifications and/or
translated into another language.

A "Secondary Section" is a named appendix or a front-matter section of the
Document that deals exclusively with the relationship of the publishers or
authors of the Document to the Document's overall subject (or to related
matters) and contains nothing that could fall directly within that overall
subject. (Thus, if the Document is in part a textbook of mathematics, a
Secondary Section may not explain any mathematics.) The relationship could be a
matter of historical connection with the subject or with related matters, or of
legal, commercial, philosophical, ethical or political position regarding them.

The "Invariant Sections" are certain Secondary Sections whose titles are
designated, as being those of Invariant Sections, in the notice that says that
the Document is released under this License. If a section does not fit the
above definition of Secondary then it is not allowed to be designated as
Invariant. The Document may contain zero Invariant Sections. If the Document
does not identify any Invariant Sections then there are none.

The "Cover Texts" are certain short passages of text that are listed, as
Front-Cover Texts or Back-Cover Texts, in the notice that says that the
Document is released under this License. A Front-Cover Text may be at most 5
words, and a Back-Cover Text may be at most 25 words.

A "Transparent" copy of the Document means a machine-readable copy, represented
in a format whose specification is available to the general public, that is
suitable for revising the document straightforwardly with generic text editors
or (for images composed of pixels) generic paint programs or (for drawings)
some widely available drawing editor, and that is suitable for input to text
formatters or for automatic translation to a variety of formats suitable for
input to text formatters. A copy made in an otherwise Transparent file format
whose markup, or absence of markup, has been arranged to thwart or discourage
subsequent modification by readers is not Transparent. An image format is not
Transparent if used for any substantial amount of text. A copy that is not
"Transparent" is called "Opaque".

Examples of suitable formats for Transparent copies include plain ASCII without
markup, Texinfo input format, LaTeX input format, SGML or XML using a publicly
available DTD, and standard-conforming simple HTML, PostScript or PDF designed
for human modification. Examples of transparent image formats include PNG, XCF
and JPG. Opaque formats include proprietary formats that can be read and edited
only by proprietary word processors, SGML or XML for which the DTD and/or
processing tools are not generally available, and the machine-generated HTML,
PostScript or PDF produced by some word processors for output purposes only.

The "Title Page" means, for a printed book, the title page itself, plus such
following pages as are needed to hold, legibly, the material this License
requires to appear in the title page. For works in formats which do not have
any title page as such, "Title Page" means the text near the most prominent
appearance of the work's title, preceding the beginning of the body of the text.

The "publisher" means any person or entity that distributes copies of the
Document to the public.

A section "Entitled XYZ" means a named subunit of the Document whose title
either is precisely XYZ or contains XYZ in parentheses following text that
translates XYZ in another language. (Here XYZ stands for a specific section
name mentioned below, such as "Acknowledgements", "Dedications",
"Endorsements", or "History".) To "Preserve the Title" of such a section when
you modify the Document means that it remains a section "Entitled XYZ"
according to this definition.

The Document may include Warranty Disclaimers next to the notice which states
that this License applies to the Document. These Warranty Disclaimers are
considered to be included by reference in this License, but only as regards
disclaiming warranties: any other implication that these Warranty Disclaimers
may have is void and has no effect on the meaning of this License.

=== 2. VERBATIM COPYING

You may copy and distribute the Document in any medium, either commercially or
noncommercially, provided that this License, the copyright notices, and the
license notice saying this License applies to the Document are reproduced in
all copies, and that you add no other conditions whatsoever to those of this
License. You may not use technical measures to obstruct or control the reading
or further copying of the copies you make or distribute. However, you may
accept compensation in exchange for copies. If you distribute a large enough
number of copies you must also follow the conditions in section 3.

You may also lend copies, under the same conditions stated above, and you may
publicly display copies.

=== 3. COPYING IN QUANTITY

If you publish printed copies (or copies in media that commonly have printed
covers) of the Document, numbering more than 100, and the Document's license
notice requires Cover Texts, you must enclose the copies in covers that carry,
clearly and legibly, all these Cover Texts: Front-Cover Texts on the front
cover, and Back-Cover Texts on the back cover. Both covers must also clearly
and legibly identify you as the publisher of these copies. The front cover must
present the full title with all words of the title equally prominent and
visible. You may add other material on the covers in addition. Copying with
changes limited to the covers, as long as they preserve the title of the
Document and satisfy these conditions, can be treated as verbatim copying in
other respects.

If the required texts for either cover are too voluminous to fit legibly, you
should put the first ones listed (as many as fit reasonably) on the actual
cover, and continue the rest onto adjacent pages.

If you publish or distribute Opaque copies of the Document numbering more than
100, you must either include a machine-readable Transparent copy along with
each Opaque copy, or state in or with each Opaque copy a computer-network
location from which the general network-using public has access to download
using public-standard network protocols a complete Transparent copy of the
Document, free of added material. If you use the latter option, you must take
reasonably prudent steps, when you begin distribution of Opaque copies in
quantity, to ensure that this Transparent copy will remain thus accessible at
the stated location until at least one year after the last time you distribute
an Opaque copy (directly or through your agents or retailers) of that edition
to the public.

It is requested, but not required, that you contact the authors of the Document
well before redistributing any large number of copies, to give them a chance to
provide you with an updated version of the Document.

=== 4. MODIFICATIONS

You may copy and distribute a Modified Version of the Document under the
conditions of sections 2 and 3 above, provided that you release the Modified
Version under precisely this License, with the Modified Version filling the
role of the Document, thus licensing distribution and modification of the
Modified Version to whoever possesses a copy of it. In addition, you must do
these things in the Modified Version:

A. Use in the Title Page (and on the covers, if any) a title distinct from that
of the Document, and from those of previous versions (which should, if there
were any, be listed in the History section of the Document). You may use the
same title as a previous version if the original publisher of that version
gives permission.

B. List on the Title Page, as authors, one or more persons or entities
responsible for authorship of the modifications in the Modified Version,
together with at least five of the principal authors of the Document (all of
its principal authors, if it has fewer than five), unless they release you from
this requirement.

C. State on the Title page the name of the publisher of the Modified Version,
as the publisher.

D. Preserve all the copyright notices of the Document.

E. Add an appropriate copyright notice for your modifications adjacent to the
other copyright notices.

F. Include, immediately after the copyright notices, a license notice giving
the public permission to use the Modified Version under the terms of this
License, in the form shown in the Addendum below.

G. Preserve in that license notice the full lists of Invariant Sections and
required Cover Texts given in the Document's license notice.

H. Include an unaltered copy of this License.

I. Preserve the section Entitled "History", Preserve its Title, and add to it
an item stating at least the title, year, new authors, and publisher of the
Modified Version as given on the Title Page. If there is no section Entitled
"History" in the Document, create one stating the title, year, authors, and
publisher of the Document as given on its Title Page, then add an item
describing the Modified Version as stated in the previous sentence.

J. Preserve the network location, if any, given in the Document for public
access to a Transparent copy of the Document, and likewise the network
locations given in the Document for previous versions it was based on. These
may be placed in the "History" section. You may omit a network location for a
work that was published at least four years before the Document itself, or if
the original publisher of the version it refers to gives permission.

K. For any section Entitled "Acknowledgements" or "Dedications", Preserve the
Title of the section, and preserve in the section all the substance and tone of
each of the contributor acknowledgements and/or dedications given therein.

L. Preserve all the Invariant Sections of the Document, unaltered in their text
and in their titles. Section numbers or the equivalent are not considered part
of the section titles.

M. Delete any section Entitled "Endorsements". Such a section may not be
included in the Modified Version.

N. Do not retitle any existing section to be Entitled "Endorsements" or to
conflict in title with any Invariant Section.

O. Preserve any Warranty Disclaimers.

If the Modified Version includes new front-matter sections or appendices that
qualify as Secondary Sections and contain no material copied from the Document,
you may at your option designate some or all of these sections as invariant. To
do this, add their titles to the list of Invariant Sections in the Modified
Version's license notice. These titles must be distinct from any other section
titles.

You may add a section Entitled "Endorsements", provided it contains nothing but
endorsements of your Modified Version by various parties—for example,
statements of peer review or that the text has been approved by an organization
as the authoritative definition of a standard.

You may add a passage of up to five words as a Front-Cover Text, and a passage
of up to 25 words as a Back-Cover Text, to the end of the list of Cover Texts
in the Modified Version. Only one passage of Front-Cover Text and one of
Back-Cover Text may be added by (or through arrangements made by) any one
entity. If the Document already includes a cover text for the same cover,
previously added by you or by arrangement made by the same entity you are
acting on behalf of, you may not add another; but you may replace the old one,
on explicit permission from the previous publisher that added the old one.

The author(s) and publisher(s) of the Document do not by this License give
permission to use their names for publicity for or to assert or imply
endorsement of any Modified Version.

=== 5. COMBINING DOCUMENTS

You may combine the Document with other documents released under this License,
under the terms defined in section 4 above for modified versions, provided that
you include in the combination all of the Invariant Sections of all of the
original documents, unmodified, and list them all as Invariant Sections of your
combined work in its license notice, and that you preserve all their Warranty
Disclaimers.

The combined work need only contain one copy of this License, and multiple
identical Invariant Sections may be replaced with a single copy. If there are
multiple Invariant Sections with the same name but different contents, make the
title of each such section unique by adding at the end of it, in parentheses,
the name of the original author or publisher of that section if known, or else
a unique number. Make the same adjustment to the section titles in the list of
Invariant Sections in the license notice of the combined work.

In the combination, you must combine any sections Entitled "History" in the
various original documents, forming one section Entitled "History"; likewise
combine any sections Entitled "Acknowledgements", and any sections Entitled
"Dedications". You must delete all sections Entitled "Endorsements".

=== 6. COLLECTIONS OF DOCUMENTS

You may make a collection consisting of the Document and other documents
released under this License, and replace the individual copies of this License
in the various documents with a single copy that is included in the collection,
provided that you follow the rules of this License for verbatim copying of each
of the documents in all other respects.

You may extract a single document from such a collection, and distribute it
individually under this License, provided you insert a copy of this License
into the extracted document, and follow this License in all other respects
regarding verbatim copying of that document.

=== 7. AGGREGATION WITH INDEPENDENT WORKS

A compilation of the Document or its derivatives with other separate and
independent documents or works, in or on a volume of a storage or distribution
medium, is called an "aggregate" if the copyright resulting from the
compilation is not used to limit the legal rights of the compilation's users
beyond what the individual works permit. When the Document is included in an
aggregate, this License does not apply to the other works in the aggregate
which are not themselves derivative works of the Document.

If the Cover Text requirement of section 3 is applicable to these copies of the
Document, then if the Document is less than one half of the entire aggregate,
the Document's Cover Texts may be placed on covers that bracket the Document
within the aggregate, or the electronic equivalent of covers if the Document is
in electronic form. Otherwise they must appear on printed covers that bracket
the whole aggregate.

=== 8. TRANSLATION

Translation is considered a kind of modification, so you may distribute
translations of the Document under the terms of section 4. Replacing Invariant
Sections with translations requires special permission from their copyright
holders, but you may include translations of some or all Invariant Sections in
addition to the original versions of these Invariant Sections. You may include
a translation of this License, and all the license notices in the Document, and
any Warranty Disclaimers, provided that you also include the original English
version of this License and the original versions of those notices and
disclaimers. In case of a disagreement between the translation and the original
version of this License or a notice or disclaimer, the original version will
prevail.

If a section in the Document is Entitled "Acknowledgements", "Dedications", or
"History", the requirement (section 4) to Preserve its Title (section 1) will
typically require changing the actual title.

=== 9. TERMINATION

You may not copy, modify, sublicense, or distribute the Document except as
expressly provided under this License. Any attempt otherwise to copy, modify,
sublicense, or distribute it is void, and will automatically terminate your
rights under this License.

However, if you cease all violation of this License, then your license from a
particular copyright holder is reinstated (a) provisionally, unless and until
the copyright holder explicitly and finally terminates your license, and (b)
permanently, if the copyright holder fails to notify you of the violation by
some reasonable means prior to 60 days after the cessation.

Moreover, your license from a particular copyright holder is reinstated
permanently if the copyright holder notifies you of the violation by some
reasonable means, this is the first time you have received notice of violation
of this License (for any work) from that copyright holder, and you cure the
violation prior to 30 days after your receipt of the notice.

Termination of your rights under this section does not terminate the licenses
of parties who have received copies or rights from you under this License. If
your rights have been terminated and not permanently reinstated, receipt of a
copy of some or all of the same material does not give you any rights to use it.

=== 10. FUTURE REVISIONS OF THIS LICENSE

The Free Software Foundation may publish new, revised versions of the GNU Free
Documentation License from time to time. Such new versions will be similar in
spirit to the present version, but may differ in detail to address new problems
or concerns. See http://www.gnu.org/copyleft/.

Each version of the License is given a distinguishing version number. If the
Document specifies that a particular numbered version of this License "or any
later version" applies to it, you have the option of following the terms and
conditions either of that specified version or of any later version that has
been published (not as a draft) by the Free Software Foundation. If the
Document does not specify a version number of this License, you may choose any
version ever published (not as a draft) by the Free Software Foundation. If the
Document specifies that a proxy can decide which future versions of this
License can be used, that proxy's public statement of acceptance of a version
permanently authorizes you to choose that version for the Document.

=== 11. RELICENSING

"Massive Multiauthor Collaboration Site" (or "MMC Site") means any World Wide
Web server that publishes copyrightable works and also provides prominent
facilities for anybody to edit those works. A public wiki that anybody can edit
is an example of such a server. A "Massive Multiauthor Collaboration" (or
"MMC") contained in the site means any set of copyrightable works thus
published on the MMC site.

"CC-BY-SA" means the Creative Commons Attribution-Share Alike 3.0 license
published by Creative Commons Corporation, a not-for-profit corporation with a
principal place of business in San Francisco, California, as well as future
copyleft versions of that license published by that same organization.

"Incorporate" means to publish or republish a Document, in whole or in part, as
part of another Document.

An MMC is "eligible for relicensing" if it is licensed under this License, and
if all works that were first published under this License somewhere other than
this MMC, and subsequently incorporated in whole or in part into the MMC, (1)
had no cover texts or invariant sections, and (2) were thus incorporated prior
to November 1, 2008.

The operator of an MMC Site may republish an MMC contained in the site under
CC-BY-SA on the same site at any time before August 1, 2009, provided the MMC
is eligible for relicensing.

